### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProtoGhost** [ware255/Mirai-Source-Code-plus#5]
root@ip-172-31-95-36:~/Mirai-Source-Code-plus# cd scripts/
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/scripts# ./cross-compile.sh
Reading package lists... Donel-client (y/n)? Installing gcc, golang, electric-fence...
Building dependency tree
Reading state information... Done

gcc is already the newest version (4:9.3.0-1ubuntu2).
golang is already the newest version (2:1.13~1ubuntu2).
electric-fence is already the newest version (2.2.5).
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.
Creating folder /etc/xcompile
Copy cross-compiler-armv4l.tar.bz2 to /etc/xcompile
Copy cross-compiler-armv5l.tar.bz2 to /etc/xcompile
Copy cross-compiler-armv6l.tar.bz2 to /etc/xcompile
Copy cross-compiler-i586.tar.bz2 to /etc/xcompile
Copy cross-compiler-m68k.tar.bz2 to /etc/xcompile
Copy cross-compiler-mips.tar.bz2 to /etc/xcompile
Copy cross-compiler-mipsel.tar.bz2 to /etc/xcompile
Copy cross-compiler-powerpc.tar.bz2 to /etc/xcompile
Copy cross-compiler-sh4.tar.bz2 to /etc/xcompile
Copy cross-compiler-sparc.tar.bz2 to /etc/xcompile
extracting cross-compiler-armv4l.tar.bz2 ...
extracting cross-compiler-armv5l.tar.bz2 ...
extracting cross-compiler-armv6l.tar.bz2 ...
extracting cross-compiler-i586.tar.bz2 ...
extracting cross-compiler-m68k.tar.bz2 ...
extracting cross-compiler-mips.tar.bz2 ...
extracting cross-compiler-mipsel.tar.bz2 ...
extracting cross-compiler-powerpc.tar.bz2 ...
extracting cross-compiler-sh4.tar.bz2 ...
extracting cross-compiler-sparc.tar.bz2 ...
removing all tar.bz2 from /etc/xcompile ...
move cross-compiler-armv4l to armv4l ...
move cross-compiler-armv5l to armv5l ...
move cross-compiler-armv6l to armv6l ...
move cross-compiler-i586 to i586 ...
move cross-compiler-m68k to m68k ...
move cross-compiler-mips to mips ...
move cross-compiler-mipsel to mipsel ...
move cross-compiler-powerpc to powerpc ...
move cross-compiler-sh4 to sh4 ...
move cross-compiler-sparc to sparc ...
export PATH ...
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/scripts#
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/scripts# cd ..
root@ip-172-31-95-36:~/Mirai-Source-Code-plus# ls
CODE_OF_CONDUCT.md  LICENSE.md  README.md  README_ja.md  SECURITY.md  cross-compile-bin  dlr  loader  mirai  scripts
root@ip-172-31-95-36:~/Mirai-Source-Code-plus# cd mirai/
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# ls
bot  build.sh  cnc  prompt.txt  release  tools
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# ./build.sh release telnet
rm: cannot remove 'release/mirai.*': No such file or directory
rm: cannot remove 'release/miraint.*': No such file or directory
cnc/database.go:8:5: cannot find package "github.com/go-sql-driver/mysql" in any of:
        /usr/lib/go-1.13/src/github.com/go-sql-driver/mysql (from $GOROOT)
        /root/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
cnc/attack.go:10:5: cannot find package "github.com/mattn/go-shellwords" in any of:
        /usr/lib/go-1.13/src/github.com/mattn/go-shellwords (from $GOROOT)
        /root/go/src/github.com/mattn/go-shellwords (from $GOPATH)
./build.sh: line 6: i586-gcc: command not found
./build.sh: line 7: i586-strip: command not found
./build.sh: line 6: mips-gcc: command not found
./build.sh: line 7: mips-strip: command not found
./build.sh: line 6: mipsel-gcc: command not found
./build.sh: line 7: mipsel-strip: command not found
./build.sh: line 6: armv4l-gcc: command not found
./build.sh: line 7: armv4l-strip: command not found
./build.sh: line 6: armv5l-gcc: command not found
./build.sh: line 7: armv5l-strip: command not found
./build.sh: line 6: armv6l-gcc: command not found
./build.sh: line 7: armv6l-strip: command not found
./build.sh: line 6: powerpc-gcc: command not found
./build.sh: line 7: powerpc-strip: command not found
./build.sh: line 6: sparc-gcc: command not found
./build.sh: line 7: sparc-strip: command not found
./build.sh: line 6: m68k-gcc: command not found
./build.sh: line 7: m68k-strip: command not found
./build.sh: line 6: sh4-gcc: command not found
./build.sh: line 7: sh4-strip: command not found
./build.sh: line 6: i586-gcc: command not found
./build.sh: line 7: i586-strip: command not found
./build.sh: line 6: mips-gcc: command not found
./build.sh: line 7: mips-strip: command not found
./build.sh: line 6: mipsel-gcc: command not found
./build.sh: line 7: mipsel-strip: command not found
./build.sh: line 6: armv4l-gcc: command not found
./build.sh: line 7: armv4l-strip: command not found
./build.sh: line 6: armv5l-gcc: command not found
./build.sh: line 7: armv5l-strip: command not found
./build.sh: line 6: armv6l-gcc: command not found
./build.sh: line 7: armv6l-strip: command not found
./build.sh: line 6: powerpc-gcc: command not found
./build.sh: line 7: powerpc-strip: command not found
./build.sh: line 6: sparc-gcc: command not found
./build.sh: line 7: sparc-strip: command not found
./build.sh: line 6: m68k-gcc: command not found
./build.sh: line 7: m68k-strip: command not found
./build.sh: line 6: sh4-gcc: command not found
./build.sh: line 7: sh4-strip: command not found
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# source ~/.bashrc
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# ./build.sh release telnet
rm: cannot remove 'release/mirai.*': No such file or directory
rm: cannot remove 'release/miraint.*': No such file or directory
cnc/database.go:8:5: cannot find package "github.com/go-sql-driver/mysql" in any of:
        /usr/lib/go-1.13/src/github.com/go-sql-driver/mysql (from $GOROOT)
        /root/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
cnc/attack.go:10:5: cannot find package "github.com/mattn/go-shellwords" in any of:
        /usr/lib/go-1.13/src/github.com/mattn/go-shellwords (from $GOROOT)
        /root/go/src/github.com/mattn/go-shellwords (from $GOPATH)
can't find i586-gcc in $PATH
i586-strip: 'release/mirai.x86': No such file
can't find mips-gcc in $PATH
mips-strip: 'release/mirai.mips': No such file
can't find mipsel-gcc in $PATH
mipsel-strip: 'release/mirai.mpsl': No such file
can't find armv4l-gcc in $PATH
armv4l-strip: 'release/mirai.arm': No such file
can't find armv5l-gcc in $PATH
armv5l-strip: 'release/mirai.arm5n': No such file
can't find armv6l-gcc in $PATH (did you export it?)
armv6l-strip: 'release/mirai.arm7': No such file
can't find powerpc-gcc in $PATH
powerpc-strip: 'release/mirai.ppc': No such file
can't find sparc-gcc in $PATH
sparc-strip: 'release/mirai.spc': No such file
can't find m68k-gcc in $PATH
m68k-strip: 'release/mirai.m68k': No such file
can't find sh4-gcc in $PATH
sh4-strip: 'release/mirai.sh4': No such file
can't find i586-gcc in $PATH
i586-strip: 'release/miraint.x86': No such file
can't find mips-gcc in $PATH
mips-strip: 'release/miraint.mips': No such file
can't find mipsel-gcc in $PATH
mipsel-strip: 'release/miraint.mpsl': No such file
can't find armv4l-gcc in $PATH
armv4l-strip: 'release/miraint.arm': No such file
can't find armv5l-gcc in $PATH
armv5l-strip: 'release/miraint.arm5n': No such file
can't find armv6l-gcc in $PATH (did you export it?)
armv6l-strip: 'release/miraint.arm7': No such file
can't find powerpc-gcc in $PATH
powerpc-strip: 'release/miraint.ppc': No such file
can't find sparc-gcc in $PATH
sparc-strip: 'release/miraint.spc': No such file
can't find m68k-gcc in $PATH
m68k-strip: 'release/miraint.m68k': No such file
can't find sh4-gcc in $PATH
sh4-strip: 'release/miraint.sh4': No such file
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# go get github.com/go-sql-driver/mysql
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# go get github.com/mattn/go-shellwords
root@ip-172-31-95-36:~/Mirai-Source-Code-plus/mirai# ./build.sh release telnet
rm: cannot remove 'release/mirai.*': No such file or directory
rm: cannot remove 'release/miraint.*': No such file or directory
can't find i586-gcc in $PATH
i586-strip: 'release/mirai.x86': No such file
can't find mips-gcc in $PATH
mips-strip: 'release/mirai.mips': No such file
can't find mipsel-gcc in $PATH
mipsel-strip: 'release/mirai.mpsl': No such file
can't find armv4l-gcc in $PATH
armv4l-strip: 'release/mirai.arm': No such file
can't find armv5l-gcc in $PATH
armv5l-strip: 'release/mirai.arm5n': No such file
can't find armv6l-gcc in $PATH (did you export it?)
armv6l-strip: 'release/mirai.arm7': No such file
can't find powerpc-gcc in $PATH
powerpc-strip: 'release/mirai.ppc': No such file
can't find sparc-gcc in $PATH
sparc-strip: 'release/mirai.spc': No such file
can't find m68k-gcc in $PATH
m68k-strip: 'release/mirai.m68k': No such file
can't find sh4-gcc in $PATH
sh4-strip: 'release/mirai.sh4': No such file
can't find i586-gcc in $PATH
i586-strip: 'release/miraint.x86': No such file
can't find mips-gcc in $PATH
mips-strip: 'release/miraint.mips': No such file
can't find mipsel-gcc in $PATH
mipsel-strip: 'release/miraint.mpsl': No such file
can't find armv4l-gcc in $PATH
armv4l-strip: 'release/miraint.arm': No such file
can't find armv5l-gcc in $PATH
armv5l-strip: 'release/miraint.arm5n': No such file
can't find armv6l-gcc in $PATH (did you export it?)
armv6l-strip: 'release/miraint.arm7': No such file
can't find powerpc-gcc in $PATH
powerpc-strip: 'release/miraint.ppc': No such file
can't find sparc-gcc in $PATH
sparc-strip: 'release/miraint.spc': No such file
can't find m68k-gcc in $PATH
m68k-strip: 'release/miraint.m68k': No such file
can't find sh4-gcc in $PATH
sh4-strip: 'release/miraint.sh4': No such file

help me

**Comment by ware255** [comment]
LinuxってDebian系のやつ？

**Comment by ware255** [comment]
Did you add the following string to the last line in `vi ~/bashrc`?
`vi ~/bashrc`で最後の行に以下の文字列を追加しましたか？

If you haven't added it, please do so. If not, please tell us otherwise.
追加していないなら追加してください。そうでなければ、そうでないと教えてください。

```
export PATH=$PATH:/etc/xcompile/armv4l/bin
export PATH=$PATH:/etc/xcompile/armv5l/bin
export PATH=$PATH:/etc/xcompile/armv6l/bin
export PATH=$PATH:/etc/xcompile/i586/bin
export PATH=$PATH:/etc/xcompile/m68k/bin
export PATH=$PATH:/etc/xcompile/mips/bin
export PATH=$PATH:/etc/xcompile/mipsel/bin
export PATH=$PATH:/etc/xcompile/powerpc/bin
export PATH=$PATH:/etc/xcompile/powerpc-440fp/bin
export PATH=$PATH:/etc/xcompile/sh4/bin
export PATH=$PATH:/etc/xcompile/sparc/bin

export GOPATH=$HOME/go
```
